### ISSUE TITLE
Issue while using Ingress : Redirection and Response URL without a basepath.

### ISSUE THREAD

**Issue by pratikghose** [o19s/quepid#461]
I've a Quepid Service deployed in EKS cluster which I'm accessing through the following url : http://host.com/quepid/sessions/new.
I want to change this so that the path becomes http://host.com/quepid and it redirects to  http://host.com/quepid/sessions/new.
Here is my ingress file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka-quepid
  namespace: eureka-poc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
spec:
  rules:
    - host: host.com
      http:
        paths:
          - path: /quepid/(.*)
            backend:
              serviceName: quepid
              servicePort: 3000
```

When I open the url http://host.com/quepid/sessions/new, its coming up properly : 
![Screenshot 2022-01-28 at 1 48 31 PM](https://user-images.githubusercontent.com/47587605/151511916-417b3a2f-3837-4ddf-a7db-9cc41c3999e0.png)

But when I click on log in I'm getting a 404 : 
![Screenshot 2022-01-28 at 1 54 21 PM 1](https://user-images.githubusercontent.com/47587605/151512468-d738327a-bd55-41fc-8c69-f93a4171fdef.png)

As you can see the request coming from the application, have url path /user/login. The url paths differs for different scenarios for example, for logout its /logout, for any asset its assets/start-... , etc.
The same is true for all the redirects happening through the application.

We were hoping to make all the response coming from the application to have the base path /quepid attached to it, so /user/login becomes **/quepid/user/login** or /logot becomes **/quepid/logout**.

Is this possible, and if it is how can we do it?

Thank you so much for your help.
